"""0008_enums_and_case_cup_ai_fields

Revision ID: 44a9768a2991
Revises: 55e0c8caf68d
Create Date: 2026-10-07 10:35:39.270536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a9768a2991'
down_revision: Union[str, Sequence[str], None] = '55e0c8caf68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_cup_submissions', sa.Column('ai_eval_status', sa.Enum('completed', 'queued_retry', 'failed_permanent', name='aievalstatus', native_enum=False), nullable=False, server_default='completed'))
    op.add_column('case_cup_submissions', sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_cup_submissions', 'evaluated_at')
    op.drop_column('case_cup_submissions', 'ai_eval_status')
    # ### end Alembic commands ###
