"""0010_invoice_numeric_amount

Revision ID: 781635ae405f
Revises: b75045c68793
Create Date: 2026-10-07 11:01:53.537331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781635ae405f'
down_revision: Union[str, Sequence[str], None] = 'b75045c68793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.create_check_constraint('ck_invoices_amount_positive', 'invoices', 'amount > 0')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_invoices_amount_positive', 'invoices', type_='check')
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
