"""0006_sync_talent_and_visibility_schema

Revision ID: f87d1674bb0c
Revises: 0005_talent
Create Date: 2026-10-07 10:21:27.979315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.rbac

# revision identifiers, used by Alembic.
revision: str = 'f87d1674bb0c'
down_revision: Union[str, Sequence[str], None] = '0005_talent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_visibility', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('candidate_visibility', 'is_open_to_work',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candidate_visibility', 'hidden_from_company_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('talent_offers', sa.Column('candidate_user_id', app.models.rbac.GUID(), nullable=False))
    op.add_column('talent_offers', sa.Column('position_title', sa.String(), nullable=False))
    op.add_column('talent_offers', sa.Column('respond_due_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('talent_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('talent_offers_candidate_id_fkey'), 'talent_offers', type_='foreignkey')
    op.create_foreign_key(None, 'talent_offers', 'users', ['candidate_user_id'], ['id'])
    op.drop_column('talent_offers', 'candidate_id')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('talent_offers', sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'talent_offers', type_='foreignkey')
    op.create_foreign_key(op.f('talent_offers_candidate_id_fkey'), 'talent_offers', 'users', ['candidate_id'], ['id'])
    op.alter_column('talent_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('talent_offers', 'respond_due_at')
    op.drop_column('talent_offers', 'position_title')
    op.drop_column('talent_offers', 'candidate_user_id')
    op.alter_column('candidate_visibility', 'hidden_from_company_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('candidate_visibility', 'is_open_to_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('candidate_visibility', 'updated_at')
    # ### end Alembic commands ###
